StarrySky.Materials.Aurora.auroraMarch = {
  uniforms: function(){
    return {
      blueNoiseTexture: {value: null},
      numberOfAuroraRaymarchingSteps: {value: 32.0},
      auroraPromptEmission: {value: new THREE.Vector3()},
      auroraGreenEmission: {value: new THREE.Vector3()},
      auroraRedEmission: {value: new THREE.Vector3()},
      auroraEnergy: {value: 0.4},
      auroraFoldMap: {value: null},
      auroraBrightnessMap: {value: null},
      auroraRayMap: {value: null},
      auroraPoleward: {value: new THREE.Vector2(1.0, 0.0)},
      auroraCotDip: {value: 0.23},
      auroraOvalOffset: {value: 0.0},
      auroraOvalRadius: {value: 2500.0},
      auroraOvalWidth: {value: 800.0},
      auroraColumnScale: {value: 1.0},
      auroraRedScale: {value: 1.0},
      auroraHistoryMap: {value: null},
      auroraHistoryBlend: {value: 1.0},
      auroraJitter: {value: new THREE.Vector2()},
      auroraMapTexelSize: {value: new THREE.Vector2()},
      auroraFrame: {value: 0.0}
    };
  },
  vertexShader: [
    'varying vec2 vUv;',

    '//A full target quad. The cloud passes draw with a bare THREE.Camera whose matrices',
    "//are identity, so the plane's vertices are already in clip space.",
    'void main(){',
      'vUv = uv;',
      'gl_Position = vec4(position, 1.0);',
    '}',
  ].join('\n'),
  fragmentShader: function(atmosphereFunctions){
    let originalGLSL = [
    '//The aurora is marched into a view independent map of the upper hemisphere, the',
    '//same stereographic map the clouds use (see cloud-march.glsl), rather than once',
    '//per pixel in every sky pass. The sky dome, the moon pass and the metering pass',
    '//then read one texel each. The aurora only emits -- nothing lights it and nothing',
    '//in it casts a shadow -- and it hangs 100km and more overhead, so the camera',
    '//walking about underneath it moves nothing. The only thing that changes the map',
    '//is time, which is slow, so every frame blends into the last one: the blue noise',
    '//step jitter and the sub texel jitter average away over a few dozen frames.',
    '//',
    '//The aurora itself is a set of curtains: thin sheets hanging along the magnetic',
    '//field, their shape along the arc baked each frame by aurora-curtain.glsl. This',
    '//pass marches the shell they hang in, from where each ray enters the bottom of it',
    '//to where it leaves the top, on a round Earth, so low on the horizon the curtains',
    '//crowd together and foreshorten as they really do.',
    '//',
    '//AURORA_MAP_K must match CLOUD_MAP_K in cloud-march.glsl, and AURORA_MAP_K in',
    '//atmosphere-pass.glsl and AuroraRenderer.js. AURORA_CURTAIN_U_RANGE must match',
    '//aurora-curtain.glsl.',

    'varying vec2 vUv;',

    'uniform sampler2D blueNoiseTexture;',
    'uniform float numberOfAuroraRaymarchingSteps;',

    '//What each emitter looks like, in linear sRGB, per kilorayleigh, in units of the',
    '//luminance of a real dark sky (AuroraRenderer.js derives them from the CIE 1931',
    '//observer). The map is stored in these same dark-sky units; the sky passes turn',
    '//them into their own units against their own dark-sky floor.',
    'uniform vec3 auroraPromptEmission; //N2+ 427.8nm with the visible N2 first positive bands',
    'uniform vec3 auroraGreenEmission;  //O(1S) 557.7nm',
    'uniform vec3 auroraRedEmission;    //O(1D) 630.0nm and 636.4nm',
    '//How hard the incoming electrons are, 0 soft to 1 hard. Harder electrons reach',
    "//deeper, pushing the curtain's lower edge down and the pink fringe out below the",
    '//green, and leave less for the high red.',
    'uniform float auroraEnergy;',

    '//The curtains (aurora-curtain.glsl): one arc per channel, mipmapped.',
    'uniform sampler2D auroraFoldMap;',
    'uniform sampler2D auroraBrightnessMap;',
    'uniform sampler2D auroraRayMap;',
    '//Where the curtains hang, in the sky frame (x south, y up, z west). Poleward is the',
    "//horizontal direction towards the magnetic pole of the observer's hemisphere;",
    '//field lines lean that way as they descend, by the cotangent of the dip angle.',
    'uniform vec2 auroraPoleward;',
    'uniform float auroraCotDip;',
    "uniform float auroraOvalOffset; //km poleward of the observer to the oval's equatorward edge",
    'uniform float auroraOvalWidth;  //km across the oval, equatorward edge to poleward edge',
    '//Radius of the oval the arcs lie along, km. The arcs bend poleward towards their',
    '//east and west ends, which from the ground bends them down towards the poleward',
    '//horizon.',
    'uniform float auroraOvalRadius;',
    '//The storm (AuroraRenderer.js turns <sky-aurora-activity> into all of these):',
    'uniform float auroraColumnScale; //Brightness, against AURORA_COLUMN_KR',
    'uniform float auroraRedScale;    //Extra high red, which great storms carry to low latitudes',

    '//Map and temporal parameters',
    'uniform sampler2D auroraHistoryMap; //Last frame, the same size as this target',
    'uniform float auroraHistoryBlend;   //Weight of this frame, 1 throws the history away',
    'uniform vec2 auroraJitter;          //Sub texel offset this frame, [-0.5, 0.5]',
    'uniform vec2 auroraMapTexelSize;    //1 / map size',
    'uniform float auroraFrame;          //Frame counter, walks the blue noise in time',

    'const float AURORA_MAP_K = 1.0723687100246826;',
    'const float GOLDEN_RATIO_CONJUGATE = 0.61803398875;',

    'const float AURORA_CURTAIN_U_RANGE = 6400.0; //km of arc the curtain maps span',
    'const float AURORA_CURTAIN_TEXELS = 4096.0;',

    '//Where each of the four arcs sits, as a fraction of the way across the oval from',
    '//its equatorward edge.',
    'const vec4 AURORA_ARC_FRACTION = vec4(0.1, 0.35, 0.6, 0.85);',

    '//The sheet: a Gaussian this many km across (real curtains are about 1km; 3 keeps',
    '//them from vanishing between map texels), with a faint wide glow around it.',
    'const float AURORA_SHEET_WIDTH = 3.0;',
    'const float AURORA_HALO_WIDTH = 30.0;',
    'const float AURORA_HALO_AMOUNT = 0.08;',
    '//The red is mostly glow, not sheet: O(1D) lives nearly two minutes before it',
    '//emits, and drifts and blurs out of the curtain in that time.',
    'const float AURORA_RED_SHEET_AMOUNT = 0.3;',
    'const float AURORA_RED_HALO_AMOUNT = 0.1;',

    '//Emission. A curtain of brightness 1 carries this many kR of 427.8nm up its',
    '//length (the column along the field), times auroraColumnScale. Green and red are',
    '//set against it.',
    'const float AURORA_COLUMN_KR = 10.0;',

    '//The ionization profile along a field line: a Gaussian below the peak, which is',
    '//the sharp lower border, and an exponential tail above it. The peak sits lower',
    '//the harder the electrons (auroraEnergy), from about 5keV to 20keV and more.',
    'const float AURORA_PEAK_HEIGHT_SOFT = 120.0;',
    'const float AURORA_PEAK_HEIGHT_HARD = 95.0;',
    'const float AURORA_LOWER_SCALE = 5.0;',
    'const float AURORA_UPPER_SCALE = 22.0;',

    '//Green, in kR per kR of 427.8, switched off below the quenching floor: under',
    '//about 100km collisions take the O(1S) energy before it can emit, while the',
    '//prompt N2 bands go on glowing. That is the pink lower fringe.',
    'const float AURORA_GREEN_PER_PROMPT = 3.0;',
    'const vec2 AURORA_GREEN_QUENCHING = vec2(92.0, 104.0);',

    '//Red, in kR per kR of 427.8, high and wide, and strong for soft electrons.',
    'const float AURORA_RED_PEAK_HEIGHT = 240.0;',
    'const float AURORA_RED_LOWER_SCALE = 35.0;',
    'const float AURORA_RED_UPPER_SCALE = 90.0;',
    'const float AURORA_RED_PER_PROMPT_SOFT = 1.2;',
    'const float AURORA_RED_PER_PROMPT_HARD = 0.15;',

    '//The altitude the field line offset is measured from: a curtain hangs straight',
    '//above its footprint here and leans equatorward above it.',
    'const float AURORA_FOOT_HEIGHT = 100.0;',

    '//Marching steps per <sky-aurora-raymarch-steps>. The steps are cheap now -- three',
    '//texture reads -- and a grazing ray crosses 2000km of shell.',
    'const float AURORA_STEP_MULTIPLIER = 2.0;',

    '$atmosphericFunctions',

    '//Distance along a ray from radius r0 to where it leaves a sphere of the given',
    '//radius, from inside it. radius^2 - r0^2 is factored so single precision does not',
    '//take the difference of two numbers near 4e7.',
    'float raySphereExit(float r0, float cosZenith, float radius){',
      'float b = r0 * cosZenith;',
      'return -b + sqrt(max(b * b + (radius - r0) * (radius + r0), 0.0));',
    '}',

    '//Where a point in the shell hangs from: (u, v, h). v is km poleward and u km',
    '//along the arc (magnetic east) of the observer, measured on the ground, after',
    '//following the field line from the point down to AURORA_FOOT_HEIGHT; h is the',
    "//point's altitude in km.",
    'vec3 auroraFootprint(vec3 position, vec2 magneticEast){',
      'float r = length(position);',
      'float h = r - RADIUS_OF_EARTH;',
      'vec2 ground = position.xz * (RADIUS_OF_EARTH / r);',
      'ground += (h - AURORA_FOOT_HEIGHT) * auroraCotDip * auroraPoleward;',
      'return vec3(dot(ground, magneticEast), dot(ground, auroraPoleward), h);',
    '}',

    '//Emission per km of column along a field line, normalized so it integrates to 1',
    '//over altitude: a Gaussian of scale lower below the peak, an exponential of scale',
    '//upper above it. sqrt(pi) / 2 = 0.8862269.',
    'float columnProfile(float h, float peak, float lower, float upper){',
      'float x = h - peak;',
      'float shape = x < 0.0 ? exp(-x * x / (lower * lower)) : exp(-x / upper);',
      'return shape / (0.8862269 * lower + upper);',
    '}',

    '//The glow along one ray, in units of the luminance of a real dark sky: the sky',
    '//passes scale it by their own dark-sky floor when they read the map.',
    'vec3 auroraRayMarchPass(vec3 rayStartPosition, vec3 rayDirection){',
      '//From the bottom of the shell to its top. The observer is inside both.',
      'float r0 = rayStartPosition.y;',
      'float tStart = raySphereExit(r0, rayDirection.y, RADIUS_OF_AURORA_BOTTOM);',
      'float tEnd = raySphereExit(r0, rayDirection.y, RADIUS_OF_AURORA_TOP);',
      'float span = tEnd - tStart;',
      'float numberOfSteps = numberOfAuroraRaymarchingSteps * AURORA_STEP_MULTIPLIER;',

      '//Magnetic east, a right angle clockwise from poleward seen from above. In (x, z)',
      '//with x south and z west, north (-1, 0) turns to east (0, -1).',
      'vec2 magneticEast = vec2(-auroraPoleward.y, auroraPoleward.x);',

      '//How far the footprint moves per km of ray, along the arc and across it. A',
      "//step's jump along the arc picks the mip of the curtain maps, so a long step",
      '//averages the rays it jumps over; its jump across widens the sheet (keeping its',
      '//integral), so a long step cannot land between curtains and miss them. Both are',
      '//near constant along a ray, so the ends stand for the whole of it.',
      'vec3 footStart = auroraFootprint(rayStartPosition + tStart * rayDirection, magneticEast);',
      'vec3 footEnd = auroraFootprint(rayStartPosition + tEnd * rayDirection, magneticEast);',
      'vec2 footPerKm = abs(footEnd.xy - footStart.xy) / max(span, 1e-3);',

      '//Where this frame puts the curtain bottoms and how much red it leaves.',
      'float peakHeight = mix(AURORA_PEAK_HEIGHT_SOFT, AURORA_PEAK_HEIGHT_HARD, auroraEnergy);',
      'float redPerPrompt = mix(AURORA_RED_PER_PROMPT_SOFT, AURORA_RED_PER_PROMPT_HARD, auroraEnergy) * auroraRedScale;',
      'vec4 arcBase = auroraOvalOffset + AURORA_ARC_FRACTION * auroraOvalWidth;',
      'float oneOverOvalDiameter = 0.5 / auroraOvalRadius;',

      '//Stratified: one blue noise offset per texel, the same fraction into every',
      '//step, walked by the golden ratio each frame so the history averages them.',
      'float jitter = fract(texture(blueNoiseTexture, gl_FragCoord.xy * 0.0078125).r + auroraFrame * GOLDEN_RATIO_CONJUGATE);',

      '//Steps crowd towards the bottom of the shell, t going as the square of the step',
      '//index, where the sharp lower border is: about 4km steps there overhead, where an',
      '//even spacing gave 9, against a 5km edge.',
      'vec3 linearAuroraGlow = vec3(0.0);',
      'for(float i = 0.0; i < numberOfSteps; i++){',
        'float stepFraction = (i + jitter) / numberOfSteps;',
        'float dt = 2.0 * stepFraction * span / numberOfSteps;',
        'vec3 foot = auroraFootprint(rayStartPosition + (tStart + span * stepFraction * stepFraction) * rayDirection, magneticEast);',
        'float x = foot.x / AURORA_CURTAIN_U_RANGE + 0.5;',
        'if(x <= 0.0 || x >= 1.0){',
          'continue;',
        '}',

        'float lod = log2(max(footPerKm.x * dt * AURORA_CURTAIN_TEXELS / AURORA_CURTAIN_U_RANGE, 1.0));',
        'vec4 fold = textureLod(auroraFoldMap, vec2(x, 0.5), lod);',
        'vec4 brightness = textureLod(auroraBrightnessMap, vec2(x, 0.5), lod);',
        'vec4 rays = textureLod(auroraRayMap, vec2(x, 0.5), lod);',

        '//Km across from each of the four sheets, and the sheets widened by the jump.',
        'float halfStepAcross = 0.5 * footPerKm.y * dt;',
        'float sheetWidthSquared = AURORA_SHEET_WIDTH * AURORA_SHEET_WIDTH + halfStepAcross * halfStepAcross;',
        'float haloWidthSquared = AURORA_HALO_WIDTH * AURORA_HALO_WIDTH + halfStepAcross * halfStepAcross;',
        'vec4 across = foot.y - (arcBase + foot.x * foot.x * oneOverOvalDiameter + fold);',
        'vec4 acrossSquared = across * across;',
        'float sheet = dot(brightness * rays, exp(-acrossSquared / sheetWidthSquared)) * AURORA_SHEET_WIDTH * inversesqrt(sheetWidthSquared);',
        'float halo = dot(brightness, exp(-acrossSquared / haloWidthSquared)) * AURORA_HALO_WIDTH * inversesqrt(haloWidthSquared);',
        'if(sheet + halo < 1e-4){',
          'continue;',
        '}',

        '//kR of 427.8 per km of column at this height, and what rides on it.',
        'float prompt = columnProfile(foot.z, peakHeight, AURORA_LOWER_SCALE, AURORA_UPPER_SCALE);',
        'float green = AURORA_GREEN_PER_PROMPT * prompt * smoothstep(AURORA_GREEN_QUENCHING.x, AURORA_GREEN_QUENCHING.y, foot.z);',
        'float red = redPerPrompt * columnProfile(foot.z, AURORA_RED_PEAK_HEIGHT, AURORA_RED_LOWER_SCALE, AURORA_RED_UPPER_SCALE);',

        'vec3 curtainEmission = (sheet + AURORA_HALO_AMOUNT * halo) * (prompt * auroraPromptEmission + green * auroraGreenEmission);',
        'vec3 redEmission = (AURORA_RED_SHEET_AMOUNT * sheet + AURORA_RED_HALO_AMOUNT * halo) * red * auroraRedEmission;',
        'linearAuroraGlow += dt * (curtainEmission + redEmission);',
      '}',

      '//In dark-sky luminance units: 1 is the brightness of a real moonless sky.',
      'return (AURORA_COLUMN_KR * auroraColumnScale) * linearAuroraGlow;',
    '}',

    'void main(){',
      '//Stereographic projection from the nadir, as in cloud-march.glsl. The map is the',
      '//same size as its history, so this texel reads its own history texel directly.',
      'vec2 uv = vUv + auroraJitter * auroraMapTexelSize;',
      'vec2 p = (2.0 * uv - 1.0) * AURORA_MAP_K;',
      'float pSquared = dot(p, p);',
      'vec3 rayDirection = vec3(2.0 * p.x, 1.0 - pSquared, 2.0 * p.y) / (1.0 + pSquared);',

      '//The aurora only ever sits above the horizon; the guard band below stays empty.',
      'vec3 glow = vec3(0.0);',
      'if(rayDirection.y > 0.0){',
        'glow = auroraRayMarchPass(vec3(0.0, RADIUS_OF_EARTH, 0.0), rayDirection);',
      '}',

      'vec3 history = texelFetch(auroraHistoryMap, ivec2(gl_FragCoord.xy), 0).rgb;',
      'gl_FragColor = vec4(mix(history, glow, auroraHistoryBlend), 1.0);',
    '}',
    ];

    let updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      updatedLines.push(originalGLSL[i].replace(/\$atmosphericFunctions/g, atmosphereFunctions));
    }

    return updatedLines.join('\n');
  }
};
