StarrySky.Materials.Clouds.cloudMarch = {
  uniforms: function(){
    return {
      sunPosition: {value: new THREE.Vector3()},
      moonPosition: {value: new THREE.Vector3()},
      sunHorizonFade: {value: 1.0},
      moonHorizonFade: {value: 1.0},
      scatteringSunIntensity: {value: 20.0},
      scatteringMoonIntensity: {value: 1.4},
      moonLightColor: {value: new THREE.Vector3()},
      mieInscatteringSum: {value: null},
      rayleighInscatteringSum: {value: null},
      transmittance: {value: null},
      blueNoiseTexture: {value: null},
      numberOfCloudMarchSteps: {value: 32.0},
      cloudShadowMap: {value: null},
      cloudShadowMapExtent: {value: 64000.0},

      //cloud-density.glsl
      cloudBaseNoise: {value: null},
      cloudDetailNoise: {value: null},
      cloudWeatherMap: {value: null},
      cloudCoverage: {value: 0.5},
      cloudType: {value: 0.5},
      cloudStartHeight: {value: 1000.0},
      cloudEndHeight: {value: 2500.0},
      cloudFadeInEndPercent: {value: 0.1},
      cloudFadeOutStartPercent: {value: 0.9},
      cloudCutoffDistance: {value: 160000.0},
      cloudObserverRadius: {value: 6366700.0},
      cloudNoiseOffset: {value: new THREE.Vector2()},
      cloudWindDirection: {value: new THREE.Vector2(1.0, 0.0)},
      midCloudCoverage: {value: 0.0},
      midCloudType: {value: 0.0},
      midCloudHeight: {value: 4000.0},

      cloudJitter: {value: new THREE.Vector2()},
      cloudMarchTexelSize: {value: new THREE.Vector2()},
      cloudFrame: {value: 0.0},
      cloudCheckerboardParity: {value: -1},
      cloudAmbientPass: {value: false},
      cloudMidSkyPass: {value: false},
      cloudPreviousMap: {value: null},
      cloudMidSkyMap: {value: null},
      cloudAmbientMap: {value: null},
      cloudGroundAlbedo: {value: new THREE.Vector3(0.05, 0.02, 0.0)}
    };
  },
  vertexShader: [
    'varying vec2 vUv;',

    '//A full target quad. The cloud passes draw with a bare THREE.Camera whose matrices',
    "//are identity, so the plane's vertices are already in clip space.",
    'void main(){',
      'vUv = uv;',
      'gl_Position = vec4(position, 1.0);',
    '}',
  ].join('\n'),
  fragmentShader: function(atmosphereFunctions){
    let originalGLSL = [
    'precision highp sampler3D;',

    '//Clouds are marched into a view independent map of the upper hemisphere rather',
    '//than per screen pixel. One map then serves the sky dome, the sun pass, the moon',
    '//pass and both eyes in VR, and turning your head needs no reprojection at all.',
    '//This pass marches the map at half resolution; cloud-resolve.glsl then upsamples',
    '//it with a temporal filter. What the clouds ARE -- coverage, species, noise -- lives',
    '//in cloud-density.glsl, shared with the cloud shadow map; this file is only about',
    '//marching through them and lighting them.',
    '//',
    '//The map is a stereographic projection from the nadir, which needs no trig in',
    '//either direction and is conformal, so texels stay square. It puts twice as many',
    '//texels per degree on the horizon as at the zenith -- the horizon is where clouds',
    '//are foreshortened and where people actually look. THETA_MAX is 94 degrees from',
    '//the zenith, so four degrees below the horizon are kept as a guard band for the',
    '//bilinear filter. CLOUD_MAP_K = tan(THETA_MAX / 2), and it must match the',
    '//constant of the same name in cloud-resolve.glsl, atmosphere-pass.glsl and',
    '//CloudRenderer.js.',

    'varying vec2 vUv;',

    'uniform vec3 sunPosition;',
    'uniform vec3 moonPosition;',
    'uniform float sunHorizonFade;',
    'uniform float moonHorizonFade;',
    'uniform float scatteringMoonIntensity;',
    'uniform float scatteringSunIntensity;',
    'uniform vec3 moonLightColor;',
    'uniform sampler3D mieInscatteringSum;',
    'uniform sampler3D rayleighInscatteringSum;',
    'uniform sampler2D transmittance;',
    'uniform sampler2D blueNoiseTexture;',
    'uniform float numberOfCloudMarchSteps;',

    '//Map and temporal parameters',
    'uniform vec2 cloudJitter;           //Sub texel offset this frame, in march texels, [-0.5, 0.5]',
    'uniform vec2 cloudMarchTexelSize;   //1 / march map size',
    'uniform float cloudFrame;           //Frame counter, drives the temporal blue noise walk',
    '//Checkerboard: the march target is half as wide as the march map, and each texel of it',
    '//marches one of a horizontal pair -- the left one where the row plus this parity is even,',
    '//the right one where it is odd. The resolve knows the pattern and fills the gaps from',
    '//the neighbours and the history. -1 marches every texel, as the mid deck pass does.',
    'uniform int cloudCheckerboardParity;',

    '//Sky light (cloudMeanSkyRadiance). Each frame this same material is drawn twice more',
    '//before the march: into a 32^2 map of the mid deck alone (cloudMidSkyPass: the low deck',
    '//switched off, no jitter), and into three texels holding the mean radiance of three',
    '//skies (cloudAmbientPass). The march reads those texels back.',
    'uniform bool cloudAmbientPass;',
    'uniform bool cloudMidSkyPass;',
    "uniform sampler2D cloudPreviousMap;  //Last frame's resolved map, both decks",
    "uniform sampler2D cloudMidSkyMap;    //Last frame's mid deck alone",
    'uniform sampler2D cloudAmbientMap;   //3 x 1, see cloudMeanSkyRadiance',
    'uniform vec3 cloudGroundAlbedo;      //<sky-ground-color>, linear',

    '//A second output: how far away the cloud in each texel is, for the temporal resolve',
    '//to reproject it by (cloud-resolve.glsl). Kilometres, so a half float holds it to a',
    '//tenth of a percent. Written as 0 where there is no cloud.',
    'layout(location = 1) out highp vec4 cloudDepthOutput;',
    'float cloudMarchDepth = 0.0;',
    '//The march map texel this fragment stands for, which is not gl_FragCoord under the checkerboard.',
    'ivec2 cloudMarchTexel;',

    'const float CLOUD_MAP_K = 1.0723687100246826;',
    'const float GOLDEN_RATIO_CONJUGATE = 0.61803398875;',

    '//Step length is ADAPTIVE. Inside cloud a step is the tag layer thickness divided by',
    '//<sky-cloud-raymarch-steps> (47m by default), growing with distance by this many',
    '//meters per meter so far clouds, which are small on screen, cost less. The old',
    '//march spread a fixed step count over the whole path through the layer, which at',
    '//low elevations is 15 to 60km -- steps of 250m and more, three or four samples',
    '//across a kilometre wide cumulus, and the banding and shimmer that came with it.',
    'const float CLOUD_STEP_GROWTH = 0.004;',

    '//Through clear air the march strides this many steps at a time on the cheap',
    '//density, after this many empty samples in a row, and backs up when it lands in',
    '//cloud so the leading edge is still met at the fine step.',
    'const float CLOUD_EMPTY_STRIDE = 3.0;',
    'const int CLOUD_EMPTY_RUN_BEFORE_STRIDE = 2;',

    '//Hard ceiling on loop iterations. Opaque cloud ends the march early, and clear air',
    '//is crossed in strides, so this is rarely reached; when it is, it is on grazing',
    '//rays out at the horizon where the clouds have already faded into the haze.',
    'const int MAX_CLOUD_MARCH_STEPS = 192;',

    '//The lit skin of a cloud is only 5 to 20m deep, but out past 12km a step is 160m',
    '//and more, so the first sample inside a cloud landed anywhere from its sunlit face',
    "//to well inside it, wherever this frame's jitter put it -- the far clouds shimmered",
    '//even with the sky stopped. So on entering a cloud the march bisects back to its',
    '//surface on the cheap density and comes through the skin at this fraction of the',
    '//base step, at every distance, until the view transmittance falls below',
    '//CLOUD_SKIN_TRANSMITTANCE. Measured against letting the skin step grow with',
    '//distance (a quarter of the grown step) and stopping at 0.5: that was about 5% of',
    '//the frame, this about 20%, for a third less horizon shimmer again.',
    'const float CLOUD_SKIN_STEP_FRACTION = 0.5;',
    'const float CLOUD_SKIN_TRANSMITTANCE = 0.2;',
    'const int CLOUD_SKIN_BISECTIONS = 4;',

    '$atmosphericFunctions',

    '$cloudDensityFunctions',

    'float henyeyGreenstein(float g, float cosTheta){',
      'float t = 1.0 + g * g - 2.0 * g * cosTheta;',
      'return ONE_OVER_FOUR_PI * (1.0 - g * g) / (t * sqrt(t));',
    '}',

    '//Two lobe phase function (takram three-clouds): a forward lobe for the bright',
    '//silver edges towards the sun and a gentle backward lobe for the lit faces away',
    '//from it. attenuation scales both g towards isotropic for the higher multiple',
    '//scattering octaves, which have been scattered round too many times to remember',
    '//where the light came from.',
    'const float CLOUD_PHASE_FORWARD_G = 0.7;',
    'const float CLOUD_PHASE_BACKWARD_G = -0.2;',
    'const float CLOUD_PHASE_MIX = 0.5;',
    'float cloudPhase(float cosTheta, float attenuation){',
      'return mix(henyeyGreenstein(CLOUD_PHASE_FORWARD_G * attenuation, cosTheta), henyeyGreenstein(CLOUD_PHASE_BACKWARD_G * attenuation, cosTheta), CLOUD_PHASE_MIX);',
    '}',

    "//Multiple scattering, Wrenninge's octaves (Oz: The Great and Volumetric, 2013) as in",
    '//Frostbite, Nubis and takram: each octave carries half the energy of the one before,',
    '//sees half the optical depth to the light, and half the anisotropy. Eight octaves is',
    "//takram's high preset. It is the far octaves that let light soak deep into a thick",
    '//cloud, so its shadow side glows grey instead of going black; with only two, the',
    '//missing energy had to be put back by hand with gain knobs.',
    '//',
    '//Deep inside a big cloud even eight octaves fall short: they decay exponentially,',
    '//and 1.5km of cumulus between a base and the sun is an optical depth of about 45,',
    '//where the last octave is down to 1/128 * e^-0.35. Diffusion theory has the true',
    '//asymptote, a transmission of 1 / (1 + 0.75 (1 - g) tau) through a slab, with g',
    '//about 0.85 for cloud droplets -- 17% at tau 45, which is why the base of a sunlit',
    '//cumulus is grey rather than black. Without it the bases were lit by the blue sky',
    '//alone and read as translucent blue.',
    '//',
    '//At full strength, though, it took over from a tau of about 3 and lit every shadow',
    '//side and base at a quarter of a sunlit face, well ahead of the octaves (at the',
    '//tau of 16 the density probe finds under a cumulus, 0.029 against 0.007). The slab',
    '//transmission is the light that makes it out through the far side; the radiance',
    '//scattered at a point inside is less. CLOUD_DIFFUSION_WEIGHT scales it down, so the',
    '//floor only catches the deep interior and the lit skin keeps the octaves.',
    '//',
    '//Returned split in two, the first octave and everything else, since the two see the',
    "//mid deck's shadow at different sharpness (midCloudShadow).",
    'const int CLOUD_MS_OCTAVES = 8;',
    'const float CLOUD_DIFFUSION_K = 0.11;',
    'const float CLOUD_DIFFUSION_WEIGHT = 0.5;',
    '//',
    '//The phase of each octave depends only on the angle between the ray and the light,',
    '//which is the same at every step of a ray, so cloudPhaseOctaves works them out once per',
    '//ray and light: sixteen Henyey-Greensteins, each with a square root and a divide, had',
    '//been evaluated again at every lit step.',
    'void cloudPhaseOctaves(float cosTheta, out float phases[CLOUD_MS_OCTAVES]){',
      'float c = 1.0;',
      'for(int i = 0; i < CLOUD_MS_OCTAVES; ++i){',
        'phases[i] = cloudPhase(cosTheta, c);',
        'c *= 0.5;',
      '}',
    '}',

    'vec2 cloudMultipleScattering(float opticalDepth, float phases[CLOUD_MS_OCTAVES]){',
      'float scattering = 0.0;',
      'float a = 1.0;',
      'float b = 1.0;',
      'for(int i = 0; i < CLOUD_MS_OCTAVES; ++i){',
        'scattering += a * exp(-opticalDepth * b) * phases[i];',
        'a *= 0.5;',
        'b *= 0.5;',
      '}',
      'float single = exp(-opticalDepth) * phases[0];',
      'scattering = max(scattering, CLOUD_DIFFUSION_WEIGHT * ONE_OVER_FOUR_PI / (1.0 + CLOUD_DIFFUSION_K * opticalDepth));',
      'return vec2(single, scattering - single);',
    '}',

    '//Optical depth from a point towards a light. Five segments, each twice the length of',
    '//the one before (40m to 640m, 1.24km in all), the first two on the full density so',
    '//neighbouring billows shade each other, the rest on the cheap one. Towering species',
    '//add a long segment that reaches up through the tower (longReach grows with the',
    "//species' depth; 1 for cumulus, which does not need it). Each sample sits at the",
    '//middle of its segment. They used to slide along it from frame to frame, for the',
    '//temporal filter to integrate, but under a base, at a tau near 16, exp(-tau) swings',
    '//so far with where the samples land that the filter left a mottle of light and dark',
    '//cells across it; midpoints showed no banding in its place.',
    'float cloudLightOpticalDepth(vec3 p, vec3 light, float t, float longReach){',
      'float opticalDepth = 40.0 * cloudDensityFull(p + light * 20.0, t)',
        '+ 80.0 * cloudDensityFull(p + light * 80.0, t)',
        '+ 160.0 * cloudDensityCheap(p + light * 200.0, t)',
        '+ 320.0 * cloudDensityCheap(p + light * 440.0, t)',
        '+ 640.0 * cloudDensityCheap(p + light * 920.0, t);',
      'if(longReach > 1.0){',
        'float longLength = 1800.0 * (longReach - 1.0);',
        'opticalDepth += longLength * cloudDensityCheap(p + light * (1240.0 + 0.5 * longLength), t);',
      '}',
      'return opticalDepth;',
    '}',

    '//How much of a light gets through the mid deck to a point below it, from the shadow',
    '//map (cloud-shadow-map.glsl). Two answers: sharp for the light scattered once, near',
    '//the surface of the cloud it lands on, and soft for the multiple scattering, which',
    '//has wandered a few hundred meters through that cloud first and so no longer knows',
    '//exactly where the shadow edge was. Read sharp everywhere, shadow lanes ran straight',
    '//through the bodies of the cumulus below.',
    '//',
    '//Each part is blurred by its own physics, by reading a coarser mip:',
    '//  direct   the unscattered beam, blurred by the size of the light, 0.27 degrees',
    '//           in radius for the sun and moon alike -- 10 to 20m at 2km -- but by no',
    '//           less than CLOUD_DIRECT_SHADOW_MIN_BLUR. At its true sharpness the dappled',
    '//           sunlight through an altocumulus deck lay on the cumulus below as flat',
    '//           warm and grey patches with hard edges, which read as a posterized palette.',
    '//  diffuse  scattered forward through the deck and out of its base in a wide,',
    '//           nearly Lambertian cone, so a point below sees it averaged over a disk',
    "//           about as wide as its drop below the deck: half of a Lambertian disk's",
    '//           light arrives from within a radius equal to the drop',
    '//  interior the multiple scattering octaves also see the direct beam smeared over',
    '//           CLOUD_INTERIOR_SHADOW_BLUR, the scale light diffuses over inside cumulus.',
    '//           The transport mean free path there is 1 / (sigma (1 - g)), 70 to 130m,',
    '//           and diffused light spreads sideways about as far as it has gone in: a',
    '//           kilometre or so into the bodies we see. 250m, the scale of the skin,',
    '//           still printed the altocumulus pattern on them.',
    '//The first, exact form sampled the deck at five points: its diffuse floor could not',
    '//blur (five points kilometres apart only average five unrelated spots), and the',
    '//sharp direct beam cut every edge anyway.',
    'uniform sampler2D cloudShadowMap;',
    'uniform float cloudShadowMapExtent;     //Meters of ground the map spans, edge to edge',
    'const float CLOUD_LIGHT_ANGULAR_RADIUS = 0.00465;',
    'const float CLOUD_INTERIOR_SHADOW_BLUR = 1000.0;',
    'const float CLOUD_DIRECT_SHADOW_MIN_BLUR = 150.0;',
    'vec2 midCloudShadow(vec3 p, vec3 light, bool isMoon){',
      'if(midCloudCoverage <= 0.0){',
        'return vec2(1.0);',
      '}',
      'float h = cloudHeight(p);',
      '//Inside the deck, its own cells shade each other through the light march.',
      'if(h >= midCloudBase()){',
        'return vec2(1.0);',
      '}',
      'float middle = 0.5 * (midCloudBase() + midCloudTop());',
      'float cosLight = max(dot(light, cloudLocalUp(p)), 0.05);',
      'float drop = middle - h;',
      'float reach = drop / cosLight;',
      'vec2 uv = (p.xz + light.xz * reach) / cloudShadowMapExtent + 0.5;',
      'float texel = cloudShadowMapExtent / float(textureSize(cloudShadowMap, 0).x);',

      '//Mip level for a blur of this radius: a mip texel is its diameter.',
      'float directRadius = max(reach * CLOUD_LIGHT_ANGULAR_RADIUS, CLOUD_DIRECT_SHADOW_MIN_BLUR);',
      'float lodDirect = log2(max(2.0 * directRadius / texel, 1.0));',
      'float lodInterior = log2(max(2.0 * max(directRadius, CLOUD_INTERIOR_SHADOW_BLUR) / texel, 1.0));',
      'float lodDiffuse = log2(max(2.0 * drop / texel, 1.0));',
      'vec4 sharp = textureLod(cloudShadowMap, uv, lodDirect);',
      'vec4 interior = textureLod(cloudShadowMap, uv, lodInterior);',
      'vec4 diffuse = textureLod(cloudShadowMap, uv, lodDiffuse);',

      "//Past the edge of the map, the deck's mean over the whole map. The map grows as the",
      '//light gets lower (CloudRenderer), so this is only ever for far clouds; over a narrow',
      '//band at the edge it cut sunset cumulus into hard orange and grey patches.',
      'vec4 mean = textureLod(cloudShadowMap, vec2(0.5), 16.0);',
      'float outside = smoothstep(0.3, 0.5, max(abs(uv.x - 0.5), abs(uv.y - 0.5)));',
      'sharp = mix(sharp, mean, outside);',
      'interior = mix(interior, mean, outside);',
      'diffuse = mix(diffuse, mean, outside);',

      'vec2 d = isMoon ? vec2(sharp.b, interior.b) : vec2(sharp.r, interior.r);',
      'return d + (isMoon ? diffuse.a : diffuse.g);',
    '}',

    '//Sky radiance towards a direction, from the same inscattering tables and in the same',
    '//units as the sky itself (and the fog below), for one light.',
    'vec3 cloudSkyRadiance(vec3 direction, vec3 lightPosition, float yObserver, sampler3D mieTable, sampler3D rayleighTable){',
      'vec3 uv3 = vec3(parameterizationOfCosOfViewZenithToX(max(direction.y, 0.0)), yObserver, parameterizationOfCosOfSourceZenithToZ(lightPosition.y));',
      'float cosTheta = dot(direction, lightPosition);',
      'float miePhase = miePhaseFunction(cosTheta);',
      '//Soft cap on the Mie peak, as for the fog: one of these samples landing near the',
      '//sun would otherwise have it dominate the whole average.',
      'miePhase = miePhase / (1.0 + miePhase * 0.1);',
      'return miePhase * texture(mieTable, uv3).rgb + rayleighPhaseFunction(cosTheta) * texture(rayleighTable, uv3).rgb;',
    '}',

    "//The sky's own light, with the same fades as the sky pass and the fog below.",
    'vec3 cloudSkySunLight(){',
      'return vec3(sunHorizonFade * sunHorizonFade * smoothstep(-0.10, -0.02, sunPosition.y) * scatteringSunIntensity);',
    '}',

    'vec3 cloudSkyMoonLight(){',
      'return moonHorizonFade * moonHorizonFade * smoothstep(-0.10, -0.02, moonPosition.y) * scatteringMoonIntensity * moonLightColor;',
    '}',

    '//Mean radiance of the upper hemisphere as it actually looks from where the light',
    '//lands, in three versions, one per texel of cloudAmbientMap:',
    '//  0  the clear sky: what the mid deck sees, with nothing above it',
    '//  1  the clear sky behind the mid deck: what the low clouds see. It was the clear sky',
    '//     alone, so after sunset a cumulus under an altocumulus deck glowing pink could',
    '//     not see the glow and stayed a dark silhouette.',
    "//  2  everything, from last frame's resolved map: what the ground sees, for the bounce",
    '//     light under the clouds.',
    '//Not the resolved map for the low clouds as well: that is the view from the ground, of',
    '//the dark undersides of the cumulus, and near the horizon mostly of cumulus -- none of',
    '//which a cumulus two kilometres up can see. Tried: it darkened every cloud, and took',
    '//the bright twilight horizon away from them.',
    '//',
    "//The maps are premultiplied and in the sky's own units, so each direction is",
    '//sky (1 - a) + rgb. Clouds lit by other clouds is a feedback loop, but a stable one:',
    '//sky light is at most half of what lights a cloud, so it settles in a frame or two.',
    '//Over 144 directions uniform in solid angle (twelve rings evenly spaced in the cosine',
    '//of the zenith angle): altocumulus cells are small enough that a dozen directions, as',
    '//there were, would flicker as they drifted across.',
    'vec3 cloudMeanSkyRadiance(int sky){',
      'float yObserver = parameterizationOfHeightToY(cloudObserverRadius * METERS_TO_KM);',
      'vec3 sunLight = cloudSkySunLight();',
      'vec3 moonLight = cloudSkyMoonLight();',
      'vec3 sum = vec3(0.0);',
      'for(int ring = 0; ring < 12; ++ring){',
        'float y = (float(ring) + 0.5) / 12.0;',
        'float r = sqrt(1.0 - y * y);',
        'for(int k = 0; k < 12; ++k){',
          'float phi = PI_TIMES_TWO * (float(k) + 0.5 * float(ring & 1)) / 12.0;',
          'vec3 direction = vec3(r * cos(phi), y, r * sin(phi));',
          'vec3 skyLight = sunLight * cloudSkyRadiance(direction, sunPosition, yObserver, mieInscatteringSum, rayleighInscatteringSum);',
          'skyLight += moonLight * cloudSkyRadiance(direction, moonPosition, yObserver, mieInscatteringSum, rayleighInscatteringSum);',
          'vec2 uv = 0.5 + 0.5 * direction.xz / ((1.0 + direction.y) * CLOUD_MAP_K);',
          'vec4 cloud = vec4(0.0);',
          'if(sky == 1){',
            'cloud = textureLod(cloudMidSkyMap, uv, 0.0);',
          '}',
          'else if(sky == 2){',
            'cloud = textureLod(cloudPreviousMap, uv, 0.0);',
          '}',
          'sum += skyLight * (1.0 - cloud.a) + cloud.rgb;',
        '}',
      '}',
      'return sum / 144.0;',
    '}',

    'vec4 cloudRayMarcher(vec3 rayDirection, vec3 sunSourceColor, vec3 moonSourceColor, vec3 midSunSourceColor, vec3 midMoonSourceColor){',
      'float mu = rayDirection.y;',
      '//The ray crosses the low shell and then the mid one. Where they do not overlap the',
      '//march jumps the clear air between them (gapStart to gapEnd).',
      'const float CLOUD_NO_INTERVAL = 1e30;',
      'float lowStart = CLOUD_NO_INTERVAL;',
      'float lowEnd = -CLOUD_NO_INTERVAL;',
      'if(cloudCoverage > 0.0 && !cloudMidSkyPass){',
        'lowStart = cloudDistanceToHeight(mu, cloudShellBaseHeight());',
        'lowEnd = cloudDistanceToHeight(mu, cloudShellTopHeight());',
      '}',
      'float midStart = CLOUD_NO_INTERVAL;',
      'float midEnd = -CLOUD_NO_INTERVAL;',
      'if(midCloudCoverage > 0.0){',
        'midStart = cloudDistanceToHeight(mu, midCloudBase());',
        'midEnd = cloudDistanceToHeight(mu, midCloudTop());',
      '}',
      'float tStart = min(lowStart, midStart);',
      'float tEnd = min(max(lowEnd, midEnd), cloudCutoffDistance);',
      'if(tStart >= tEnd){',
        'return vec4(0.0);',
      '}',
      'float gapStart = lowEnd;',
      'float gapEnd = midStart;',
      'float midSwitch = midStart;',

      '//See CLOUD_STEP_GROWTH. <sky-cloud-raymarch-steps> is how many steps cross a',
      '//1500m cumulus, 47m at the default of 32; towering species step coarser',
      '//(cloudStepScale in cloud-density.glsl).',
      'const float CLOUD_STEP_REFERENCE_DEPTH = 1500.0;',
      'float baseStep = CLOUD_STEP_REFERENCE_DEPTH * cloudStepScale() / numberOfCloudMarchSteps;',
      '//How far the long shadow samples reach: 1 for cumulus, 5.5 for a 10km tower.',
      'float longShadowReach = max((cloudSpeciesTop(cloudType) - cloudSpeciesBase(cloudType)) / 1800.0, 1.0);',

      'float rayTransmittance = 1.0;',
      'vec3 luminance = vec3(0.0);',

      '//Transmittance weighted mean depth, for atmospheric perspective. First contact',
      '//put the fog at the leading wisp, which under-fogs the body behind it -- badly so',
      '//for clouds a hundred kilometres out, where the body can be kilometres deeper.',
      'float depthWeightSum = 0.0;',
      'float weightedDepth = 0.0;',

      '// Dual-light path: compute sun and moon contributions independently and',
      '// sum them at each step, so nothing jumps where the sun hands over to the moon.',
      '// Skip flags are uniform across all pixels, so the branch is free.',
      '//',
      '// Sign convention: light positions are direction vectors FROM origin TO',
      '// sun/moon. rayDirection is camera-into-scene. cosViewLight = dot(rayDir,',
      '// lightDir) is the cos of the scattering angle: +1 = looking AT light',
      '// (forward peak / silver), -1 = looking away (backward lobe).',
      'bool computeSun = dot(sunSourceColor + midSunSourceColor, vec3(1.0)) > 0.0;',
      'bool computeMoon = dot(moonSourceColor + midMoonSourceColor, vec3(1.0)) > 0.0;',
      'float cosViewSunLight = dot(rayDirection, sunPosition);',
      'float cosViewMoonLight = dot(rayDirection, moonPosition);',
      'float sunPhases[CLOUD_MS_OCTAVES];',
      'float moonPhases[CLOUD_MS_OCTAVES];',
      'cloudPhaseOctaves(cosViewSunLight, sunPhases);',
      'cloudPhaseOctaves(cosViewMoonLight, moonPhases);',

      '//Jitter starting position using blue noise (before the loop). Full-step',
      '//jitter is required -- half-step let visible banding rings through. The',
      '//buzz that full jitter leaves behind is what the TAA resolve averages out:',
      '//blue noise in space, plus a golden ratio walk in time, so every texel',
      '//visits [0, 1) evenly across frames instead of repeating one offset.',
      'float cloudBlueNoise = fract(texelFetch(blueNoiseTexture, cloudMarchTexel % 128, 0).r + cloudFrame * GOLDEN_RATIO_CONJUGATE);',
      'float t = tStart + cloudBlueNoise * max(baseStep, tStart * CLOUD_STEP_GROWTH);',

      "//Sky light, in the sky's own units: the mean radiance of the upper hemisphere, from",
      '//the same tables and with the same fades as the sky and the fog. Same for every',
      '//step of this ray, so worked out once. It used to be the hemisphere light that',
      '//lights the scene, which is gamma encoded and normalized to its own maximum --',
      '//no fixed relation to the sun at all, and the source of the grey-blue cast.',
      'float yObserver = parameterizationOfHeightToY(cloudObserverRadius * METERS_TO_KM);',
      'float fogGateSun = smoothstep(-0.10, -0.02, sunPosition.y);',
      'float fogGateMoon = smoothstep(-0.10, -0.02, moonPosition.y);',
      'vec3 clearSkyRadiance = texelFetch(cloudAmbientMap, ivec2(0, 0), 0).rgb;',
      'vec3 midSkyRadiance = texelFetch(cloudAmbientMap, ivec2(1, 0), 0).rgb;',
      'vec3 meanSkyRadiance = texelFetch(cloudAmbientMap, ivec2(2, 0), 0).rgb;',

      '//Light reflected up off the ground, for the cloud bases: the ground is lit by the',
      '//sun and moon through the atmosphere and by the whole sky (irradiance pi times its',
      "//mean radiance), and the sun's share is thinned by the clouds' own shadow, one",
      '//minus the coverage (takram). A Lambertian ground sends back albedo * E / pi, evenly',
      "//over the lower hemisphere. The albedo is the scene's own <sky-ground-color>, as the",
      "//scene's lighting uses it. It was a fixed 0.3, pale sand, ten times the default dark",
      '//soil: bounce was two thirds of what lit the darkest cloud, and lifted every',
      '//shadowed base until the clouds spanned 3.5x from shade to sunlit top instead of the',
      '//5 to 8x of real cumulus.',
      'const float CLOUD_SKY_OCCLUSION_SOFTNESS = 0.25;',
      'vec3 sunGroundIrradiance = vec3(0.0);',
      'if(computeSun){',
        'sunGroundIrradiance += sunSourceColor * max(sunPosition.y, 0.0) * texture(transmittance, vec2(parameterizationOfCosOfViewZenithToX(max(sunPosition.y, 0.0)), yObserver)).rgb;',
      '}',
      'if(computeMoon){',
        'sunGroundIrradiance += moonSourceColor * max(moonPosition.y, 0.0) * texture(transmittance, vec2(parameterizationOfCosOfViewZenithToX(max(moonPosition.y, 0.0)), yObserver)).rgb;',
      '}',
      'vec3 groundRadiance = cloudGroundAlbedo * (meanSkyRadiance + (1.0 - cloudCoverage) * (1.0 - midCloudCoverage) * sunGroundIrradiance / PI);',

      'int emptyRun = 0;',
      '//For the skin (see CLOUD_SKIN_STEP_FRACTION): how far the last step went, whether',
      '//the last sample was clear air, and where a bisected surface was found.',
      'float lastStep = 0.0;',
      'bool wasEmpty = true;',
      'float approachEnd = -1.0;',
      'float skinStep = CLOUD_SKIN_STEP_FRACTION * baseStep;',
      '//A sheet has no skin: altostratus at 0.008/m has a mean free path of 125m, and',
      '//crossing it in the 23m steps meant for the 5 to 20m lit skin of a cumulus made an',
      '//overcast of it cost half as much again as the whole low deck. In the mid deck the',
      '//step is kept to at least half a mean free path, as much as the deck is a sheet;',
      '//altocumulus is unaffected.',
      'float midSheetStep = midCloudType * 0.5 / midCloudKey(MID_CLOUD_DENSITY_SCALE);',
      'for(int i = 0; i < MAX_CLOUD_MARCH_STEPS; ++i){',
        'if(t >= tEnd){',
          'break;',
        '}',
        "//Clear air between the decks: jump to the mid deck's base, jittered like the start",
        '//of the march, and let the skin bisection find the first cell from there.',
        'if(t > gapStart && t < gapEnd){',
          'float jump = cloudBlueNoise * max(baseStep, gapEnd * CLOUD_STEP_GROWTH);',
          't = gapEnd + jump;',
          'lastStep = jump;',
          'wasEmpty = true;',
          'emptyRun = 0;',
          'continue;',
        '}',
        'vec3 currentPosition = rayDirection * t;',
        '//Deeper into a cloud, whatever lies further along is seen through less and less',
        '//of it, so the step can open up as the view transmittance falls -- up to 3x once',
        '//the ray is mostly occluded.',
        'float rayDeltaT = max(baseStep, t * CLOUD_STEP_GROWTH) * (3.0 - 2.0 * rayTransmittance);',
        '//Coming up to a surface found by bisection, or in the skin just past it, step fine.',
        'bool inSkin = t < approachEnd + skinStep || (!wasEmpty && rayTransmittance > CLOUD_SKIN_TRANSMITTANCE);',
        'if(inSkin){',
          'rayDeltaT = min(rayDeltaT, skinStep);',
        '}',
        'if(midSheetStep > 0.0 && t >= midSwitch && cloudHeight(rayDirection * t) >= midCloudBase()){',
          'rayDeltaT = max(rayDeltaT, midSheetStep);',
        '}',

        '//Empty-space skip on the weather alone, which bounds the full density (the noise',
        '//only ever erodes). A miss means there is nothing to light at this sample. In a',
        '//long run of clear air, stride further.',
        'if(!cloudMayHaveDensity(currentPosition, t)){',
          '++emptyRun;',
          'wasEmpty = true;',
          'lastStep = (emptyRun > CLOUD_EMPTY_RUN_BEFORE_STRIDE && !inSkin) ? CLOUD_EMPTY_STRIDE * rayDeltaT : rayDeltaT;',
          't += lastStep;',
          'continue;',
        '}',
        'if(emptyRun > CLOUD_EMPTY_RUN_BEFORE_STRIDE && !inSkin){',
          "//A long stride may have jumped over the cloud's leading edge; back up to one",
          '//fine step past the last empty sample and come in at normal pace.',
          'emptyRun = 0;',
          't -= (CLOUD_EMPTY_STRIDE - 1.0) * rayDeltaT;',
          'lastStep = rayDeltaT;',
          'continue;',
        '}',
        'emptyRun = 0;',

        'float extinction = cloudDensityFull(currentPosition, t);',
        '//Just entered a cloud on a step longer than the skin step: find its surface',
        '//between the last clear sample and here, then come back in through the skin',
        '//from just outside it, jittered by a skin step rather than a whole step.',
        'if(extinction > 0.0 && wasEmpty && lastStep > 1.01 * skinStep){',
          'float outside = t - lastStep;',
          'float inside = t;',
          'for(int k = 0; k < CLOUD_SKIN_BISECTIONS; ++k){',
            'float middle = 0.5 * (outside + inside);',
            'if(cloudDensityCheap(rayDirection * middle, middle) > 0.0){',
              'inside = middle;',
            '}',
            'else{',
              'outside = middle;',
            '}',
          '}',
          'approachEnd = inside;',
          't = outside + cloudBlueNoise * skinStep;',
          'lastStep = 0.0;',
          'continue;',
        '}',
        'wasEmpty = extinction <= 0.0;',
        'lastStep = rayDeltaT;',
        'if(extinction > 0.0){',
          "//Per-sample atmospheric transmittance, looked up at this sample's own",
          '//altitude and against its own local vertical -- a cloud far out on the',
          '//curve of the Earth sees the sun at a different elevation than we do.',
          'vec3 localUp = cloudLocalUp(currentPosition);',
          'float yLightSrc = parameterizationOfHeightToY((cloudObserverRadius + cloudHeight(currentPosition)) * METERS_TO_KM);',

          "//Above the mid deck's base, its own horizon fade (see main).",
          'bool inMidDeck = t >= midSwitch && cloudHeight(currentPosition) >= midCloudBase();',
          "//Each light's block is compiled in only when CloudRenderer asks for it",
          "//(CLOUD_SUN_LIGHT, CLOUD_MOON_LIGHT). Skipped at run time, the moon's block",
          '//still cost a quarter of the frame by day -- it made the shader bigger, and a',
          '//bigger shader keeps fewer pixels in flight -- so there are three builds, and',
          '//both lights share one only through twilight.',
          'vec3 radiance = vec3(0.0);',
          '#ifdef CLOUD_SUN_LIGHT',
          'if(computeSun){',
            'vec2 uvSun = vec2(parameterizationOfCosOfViewZenithToX(max(dot(sunPosition, localUp), 0.0)), yLightSrc);',
            'vec3 sunLight = (inMidDeck ? midSunSourceColor : sunSourceColor) * texture(transmittance, uvSun).rgb;',
            'float sunOpticalDepth = cloudLightOpticalDepth(currentPosition, sunPosition, t, longShadowReach);',
            'radiance += sunLight * dot(cloudMultipleScattering(sunOpticalDepth, sunPhases), midCloudShadow(currentPosition, sunPosition, false));',
          '}',
          '#endif',
          '#ifdef CLOUD_MOON_LIGHT',
          'if(computeMoon){',
            'vec2 uvMoon = vec2(parameterizationOfCosOfViewZenithToX(max(dot(moonPosition, localUp), 0.0)), yLightSrc);',
            'vec3 moonLight = (inMidDeck ? midMoonSourceColor : moonSourceColor) * texture(transmittance, uvMoon).rgb;',
            'float moonOpticalDepth = cloudLightOpticalDepth(currentPosition, moonPosition, t, longShadowReach);',
            'radiance += moonLight * dot(cloudMultipleScattering(moonOpticalDepth, moonPhases), midCloudShadow(currentPosition, moonPosition, true));',
          '}',
          '#endif',

          '//Sky light: in-scattered isotropically from the upper hemisphere, 2 pi of',
          '//solid angle at a phase of 1 / (4 pi), so half the mean radiance -- through',
          '//whatever cloud lies above this point, 100m, 150m and 350m segments on the',
          '//cheap density. takram scales by the height fraction instead, which lit the',
          '//base of a 5km tower like the base of a small cumulus. Diffuse light arrives',
          '//from the whole hemisphere and scatters on through, so it sees a softened',
          '//extinction, like the far octaves (CLOUD_SKY_OCCLUSION_SOFTNESS).',
          '//',
          '//Three segments here and three below, not two: with two, a point flipped',
          '//between lit and occluded as one sample moved in or out of cloud, and shaded',
          '//bases broke into flat patches, a posterized palette. Jittering two samples',
          '//instead smoothed them for free but nearly doubled the frame to frame flicker;',
          '//five and four fixed ones cost 15 to 35% for no more smoothness than these.',
          'float skyOpticalDepth = 100.0 * cloudDensityCheap(currentPosition + localUp * 50.0, t) + 150.0 * cloudDensityCheap(currentPosition + localUp * 175.0, t) + 350.0 * cloudDensityCheap(currentPosition + localUp * 425.0, t);',
          'radiance += 0.5 * (inMidDeck ? clearSkyRadiance : midSkyRadiance) * exp(-CLOUD_SKY_OCCLUSION_SOFTNESS * skyOpticalDepth);',

          '//Ground bounce, from the lower hemisphere the same way, through whatever cloud',
          '//lies below this point.',
          'float groundOpticalDepth = 80.0 * cloudDensityCheap(currentPosition - localUp * 40.0, t) + 100.0 * cloudDensityCheap(currentPosition - localUp * 130.0, t) + 120.0 * cloudDensityCheap(currentPosition - localUp * 240.0, t);',
          'radiance += 0.5 * groundRadiance * exp(-groundOpticalDepth);',

          '//Powder (Schneider): the thinnest wisps have too little cloud around them to',
          "//scatter much light back out towards us. takram's form, keyed on the local",
          '//extinction, so it only ever darkens the tenuous fringes -- at the density of',
          "//a cloud's body it is 1.",
          'radiance *= 1.0 - 0.8 * exp(-extinction * 150.0);',

          '//Energy conserving step integration (Hillaire, Frostbite 2016): the exact',
          '//integral over the step of a constant source, (S - S T) / sigma_t, with the',
          '//scattering coefficient equal to the extinction (cloud droplets barely absorb).',
          'float stepTransmittance = exp(-extinction * rayDeltaT);',
          'luminance += rayTransmittance * radiance * (1.0 - stepTransmittance);',
          'weightedDepth += t * rayTransmittance * (1.0 - stepTransmittance);',
          'depthWeightSum += rayTransmittance * (1.0 - stepTransmittance);',
          'rayTransmittance *= stepTransmittance;',

          '//Past 1% nothing further along the ray can show -- and whatever the ray still',
          '//had left is taken as blocked. Stopping with the 1% still stored let the sun',
          '//through the thickest cumulus: the sky pass shows the sun disk at (1 - a), and',
          '//1% of a disk thousands of times brighter than the cloud is a bright, crisp',
          '//edged disk sitting in the middle of it. Thin cloud still lets it through at',
          '//exp(-tau), the watery sun, since it never gets down here.',
          'if(rayTransmittance < 0.01){',
            'rayTransmittance = 0.0;',
            'break;',
          '}',
        '}',
        't += rayDeltaT;',
      '}',

      'if(depthWeightSum > 0.0){',
        '//Proper atmospheric perspective using the Elek/Chalmers LUT subtraction:',
        '//  S(viewer->cloud) = S(viewer->inf) - T(viewer->cloud) * S(cloud->inf)',
        "//The inscattering LUTs don't have earth shadow baked in (that's applied",
        '//post-hoc in linearAtmosphericPass), so this naturally gives shadow-free',
        '//fog for the viewer-to-cloud path.',
        '//',
        '//Both ends are looked up with their OWN view zenith: along a straight ray the',
        '//angle to the local vertical opens up by the distance over the planet radius,',
        "//which is a degree and a half for a cloud 150km out. Reusing the observer's",
        '//angle at the far end is what made distant clouds sit in the wrong fog.',
        'float meanDepth = weightedDepth / depthWeightSum;',
        'cloudMarchDepth = meanDepth;',
        'vec3 cloudPoint = rayDirection * meanDepth;',
        'vec3 cloudUp = cloudLocalUp(cloudPoint);',
        'float observerR = cloudObserverRadius * METERS_TO_KM;',
        'float cloudR = observerR + cloudHeight(cloudPoint) * METERS_TO_KM;',
        'float xParamObs = parameterizationOfCosOfViewZenithToX(max(mu, 0.0));',
        'float xParamCloud = parameterizationOfCosOfViewZenithToX(max(dot(rayDirection, cloudUp), 0.0));',
        'float yObs = parameterizationOfHeightToY(observerR);',
        'float yCloud = parameterizationOfHeightToY(cloudR);',

        '//Viewer-to-cloud transmittance: T(v->c) = T(v->inf) / T(c->inf)',
        'vec3 T_obs = texture(transmittance, vec2(xParamObs, yObs)).rgb;',
        'vec3 T_cloud = texture(transmittance, vec2(xParamCloud, yCloud)).rgb;',
        'vec3 T_path = T_obs / max(T_cloud, vec3(0.001));',

        '//Attenuate cloud luminance by viewer-to-cloud extinction',
        'luminance *= T_path;',

        '//Compute inscattering along viewer-to-cloud path for sun',
        'float zSun = parameterizationOfCosOfSourceZenithToZ(sunPosition.y);',
        'vec3 uv3ObsSun = vec3(xParamObs, yObs, zSun);',
        'vec3 uv3CloudSun = vec3(xParamCloud, yCloud, parameterizationOfCosOfSourceZenithToZ(dot(sunPosition, cloudUp)));',
        'vec3 fogMieSun = max(texture(mieInscatteringSum, uv3ObsSun).rgb - T_path * texture(mieInscatteringSum, uv3CloudSun).rgb, vec3(0.0));',
        'vec3 fogRaySun = max(texture(rayleighInscatteringSum, uv3ObsSun).rgb - T_path * texture(rayleighInscatteringSum, uv3CloudSun).rgb, vec3(0.0));',
        'float cosViewSun = dot(rayDirection, sunPosition);',
        '// Soft-saturate the Mie phase peak on the viewer->cloud fog inscatter',
        '// path. miePhaseFunction (Cornette-Shanks, g~0.76) peaks at ~50 at',
        '// cos=1 (looking toward the sun), which produced the "arc light" /',
        '// "edges glowing" behaviour at sunset where the short fog path',
        '// multiplied by the unbounded peak overwhelmed cloud silhouettes.',
        '// Soft form `x / (1 + x/CAP)` smoothly asymptotes to CAP=10 with',
        '// no kink -- at cos=1 reduces ~50->8.3, at cos=0.9 reduces ~4.6->3.2,',
        '// perpendicular angles unaffected. Hard min(x, 10) would create a',
        '// visible ring at the cap transition.',
        'float miePhaseSun = miePhaseFunction(cosViewSun);',
        'float cappedMiePhaseSun = miePhaseSun / (1.0 + miePhaseSun * 0.1);',
        '// Extra smoothstep gate on cloud-fog (in addition to sunHorizonFade^2):',
        '// C++ horizonFade only zeros at sun 18 deg below horizon, so at nautical',
        '// twilight (sun -6 deg to -10 deg) sunHorizonFade is still 0.4-0.7. Squared',
        '// and times scatteringSunIntensity (default 20), the fog term gets a',
        '// ~3-10x multiplier on dim-blue Rayleigh LUT values -- visible blue',
        '// tint on cloud bodies even with sky still nearly black. The sky',
        '// pass uses sunHorizonFade^2 unchanged because it SHOULD glow during',
        "// astronomical twilight; clouds shouldn't pick up the same scatter",
        "// since they're being viewed against an already-near-dark sky.",
        '// Cuts fog at sun -6 deg (smoothstep -0.10 -> -0.02 in y units, ~ -5.7 deg -> -1.1 deg).',
        'vec3 fogSun = sunHorizonFade * sunHorizonFade * fogGateSun * scatteringSunIntensity * (cappedMiePhaseSun * fogMieSun + rayleighPhaseFunction(cosViewSun) * fogRaySun);',

        '//Compute inscattering along viewer-to-cloud path for moon',
        'float zMoon = parameterizationOfCosOfSourceZenithToZ(moonPosition.y);',
        'vec3 uv3ObsMoon = vec3(xParamObs, yObs, zMoon);',
        'vec3 uv3CloudMoon = vec3(xParamCloud, yCloud, parameterizationOfCosOfSourceZenithToZ(dot(moonPosition, cloudUp)));',
        'vec3 fogMieMoon = max(texture(mieInscatteringSum, uv3ObsMoon).rgb - T_path * texture(mieInscatteringSum, uv3CloudMoon).rgb, vec3(0.0));',
        'vec3 fogRayMoon = max(texture(rayleighInscatteringSum, uv3ObsMoon).rgb - T_path * texture(rayleighInscatteringSum, uv3CloudMoon).rgb, vec3(0.0));',
        'float cosViewMoon = dot(rayDirection, moonPosition);',
        '// Same soft-cap as the sun path -- moonlight is dimmer overall but the',
        '// forward Mie peak still produces a visible bright halo around the',
        '// moon when looking through cloud fog at low altitude. Same fog gate',
        '// as sun for symmetric behavior -- moon fog dies when moon is well',
        '// below horizon rather than persisting via permissive C++ horizonFade.',
        'float miePhaseMoon = miePhaseFunction(cosViewMoon);',
        'float cappedMiePhaseMoon = miePhaseMoon / (1.0 + miePhaseMoon * 0.1);',
        'vec3 fogMoon = moonHorizonFade * moonHorizonFade * fogGateMoon * scatteringMoonIntensity * moonLightColor * (cappedMiePhaseMoon * fogMieMoon + rayleighPhaseFunction(cosViewMoon) * fogRayMoon);',

        '//The cloud light is already premultiplied (see the step integration), but the',
        '//fog in front of the cloud is a radiance, so it is weighted by how much of this',
        '//texel the cloud covers -- where the cloud is thin, the sky behind it already',
        '//carries this stretch of air.',
        'luminance += (fogSun + fogMoon) * (1.0 - rayTransmittance);',
      '}',

      '//No final * max(sunHorizonFade, moonHorizonFade): sun/moonSourceColor',
      '//are already faded via sunCloudFade/moonCloudFade in main() (so direct +',
      '//MS terms fade naturally), and fogSun/fogMoon carry their own ^2 fade.',
      '//Multiplying again here produced double-fade (fade*fade for direct,',
      '//fade^3 for fog) which collapsed twilight clouds to near-black before',
      '//the sun had even crossed the horizon.',
      'return vec4(luminance, 1.0 - rayTransmittance);',
    '}',

    'void main(){',
      'if(cloudAmbientPass){',
        'gl_FragColor = vec4(cloudMeanSkyRadiance(int(gl_FragCoord.x)), 1.0);',
        'cloudDepthOutput = vec4(0.0);',
        'return;',
      '}',

      "//Direction for this texel, nudged by this frame's sub texel jitter so that the",
      "//resolve pass accumulates genuinely new sample positions over time. The mid deck's",
      '//own little map is not resolved, so it goes without.',
      'cloudMarchTexel = ivec2(gl_FragCoord.xy);',
      'vec2 uv = vUv;',
      'if(!cloudMidSkyPass){',
        'if(cloudCheckerboardParity >= 0){',
          'cloudMarchTexel.x = 2 * cloudMarchTexel.x + ((cloudMarchTexel.y + cloudCheckerboardParity) & 1);',
        '}',
        'uv = (vec2(cloudMarchTexel) + 0.5 + cloudJitter) * cloudMarchTexelSize;',
      '}',
      'vec2 p = (2.0 * uv - 1.0) * CLOUD_MAP_K;',
      'float pSquared = dot(p, p);',
      'vec3 rayDirection = vec3(2.0 * p.x, 1.0 - pSquared, 2.0 * p.y) / (1.0 + pSquared);',

      '//Clouds only exist above the horizon, and the guard band below it stays empty.',
      'if(rayDirection.y <= 0.0){',
        'gl_FragColor = vec4(0.0);',
        'cloudDepthOutput = vec4(0.0);',
        'return;',
      '}',

      '//Cloud-illumination strength uses CLOUD-LOCAL horizon, not world horizon.',
      '//A cloud at altitude h has its horizon dipped below the world horizon by',
      '//sqrt(2h/R_earth) (small-angle approximation). For default 1000-2500m',
      '//clouds the dip is ~1.34deg; for 10km cirrus, ~3.2deg. So a moon at',
      '//-2deg world-elevation is still fully above a 10km cirrus local horizon',
      '//and should be lighting it even though it appears to be below horizon',
      '//from the ground observer perspective. The previous sunPosition.y-based',
      '//fade got this wrong (clouds went dark as soon as the light source',
      '//crossed the world horizon, regardless of cloud altitude).',
      '//',
      '//Above the cloud local horizon: full intensity (clouds are 3D',
      '//scatterers, not flat surfaces, so no Lambert cosine). Below: smoothstep',
      '//fades over a ~5.7deg band so the transition is soft. The atmospheric',
      '//transmittance LUT inside the marcher still reddens the light at low',
      '//sun, so sunset color comes through correctly without needing fade',
      '//gymnastics here.',
      'float cloudMidHeightKm = (cloudSpeciesBase(cloudType) + cloudSpeciesTop(cloudType)) * 0.0005;',
      'float cloudHorizonDip = sqrt(2.0 * cloudMidHeightKm / RADIUS_OF_EARTH);',
      'float effectiveSunY = sunPosition.y + cloudHorizonDip;',
      'float effectiveMoonY = moonPosition.y + cloudHorizonDip;',
      'float sunCloudFade = smoothstep(-0.1, 0.05, effectiveSunY);',
      'float moonCloudFade = smoothstep(-0.1, 0.05, effectiveMoonY);',
      '//The mid deck sits higher, so it keeps the light a few minutes longer after sunset.',
      'float midCloudHorizonDip = sqrt(2.0 * (midCloudBase() + midCloudTop()) * 0.0005 / RADIUS_OF_EARTH);',
      'float midSunCloudFade = smoothstep(-0.1, 0.05, sunPosition.y + midCloudHorizonDip);',
      'float midMoonCloudFade = smoothstep(-0.1, 0.05, moonPosition.y + midCloudHorizonDip);',

      '//Pre-transmittance source colors. Pass these into the cloud marcher',
      '//unmodified -- the marcher re-applies atmospheric transmittance',
      '//per-cloud-sample (which is the physically correct place since each',
      '//cloud sample is at a different altitude with a different path length',
      '//to the sun/moon).',
      'vec3 sunSourceColor = scatteringSunIntensity * vec3(1.0) * sunCloudFade;',
      '//The moon lights clouds with the same weight it lights the sky with, exactly as the',
      '//sun does: a moonlit scene is a dimmer copy of a daylit one, so moonlit cumulus',
      '//stands out silver against a dark sky the same way white cumulus stands out by',
      '//day. The old 0.3 (tuned against the retired density) left clouds as near black',
      '//silhouettes beside a bright gibbous moon.',
      'vec3 moonSourceColor = scatteringMoonIntensity * moonLightColor * moonCloudFade;',
      'vec3 midSunSourceColor = scatteringSunIntensity * vec3(1.0) * midSunCloudFade;',
      'vec3 midMoonSourceColor = scatteringMoonIntensity * moonLightColor * midMoonCloudFade;',

      '//The ray starts at the camera, which is the origin of the cloud frame. The sky',
      '//dome used to start it at the dome vertex, which pushed the origin 5km out along',
      '//the horizontal view direction and quietly stretched the cloud field towards the',
      '//horizon. Where the camera is over the ground rides in cloudNoiseOffset.',
      'vec4 cloud = cloudRayMarcher(rayDirection, sunSourceColor, moonSourceColor, midSunSourceColor, midMoonSourceColor);',
      'cloudDepthOutput = vec4(cloudMarchDepth * METERS_TO_KM, 0.0, 0.0, 1.0);',

      '//Stored premultiplied, (L * a, a), and composited as sky * (1 - a) + rgb. It has',
      '//to be premultiplied BEFORE anything filters the map: the temporal resolve',
      '//averages texels over frames and the sky samples them bilinearly, and wherever',
      '//cloud meets clear sky avg(L) * avg(a) comes out well short of avg(L * a).',
      "//The march's integral, the sum of T (1 - e^(-sigma dt)) L, is ALREADY L * a, so",
      '//it goes out as it is. Multiplying by a again, as this used to, squared the',
      '//opacity of every translucent edge: thin cloud came out dark and eaten away.',
      'gl_FragColor = cloud;',
    '}',

    ];

    let updatedLines = [];
    for(let i = 0, numLines = originalGLSL.length; i < numLines; ++i){
      let updatedGLSL = originalGLSL[i].replace(/\$atmosphericFunctions/g, atmosphereFunctions);
      updatedGLSL = updatedGLSL.replace(/\$cloudDensityFunctions/g, StarrySky.Materials.Clouds.cloudDensity.partialFragmentShader);
      updatedLines.push(updatedGLSL);
    }

    return updatedLines.join('\n');
  }
};
