StarrySky.Materials.Clouds.cloudResolve = {
  uniforms: function(){
    return {
      cloudMarchMap: {value: null},
      cloudHistoryMap: {value: null},
      cloudJitter: {value: new THREE.Vector2()},
      cloudMarchSize: {value: new THREE.Vector2()},
      cloudMarchTexelSize: {value: new THREE.Vector2()},
      cloudReprojectionShift: {value: new THREE.Vector3()},
      cloudReprojectionHeight: {value: 1750.0},
      cloudEarthRadius: {value: 6366700.0},
      cloudCutoffDistance: {value: 40000.0},
      cloudHistoryBlend: {value: 1.0},
      cloudResolveSize: {value: new THREE.Vector2()}
    };
  },
  vertexShader: [
    'varying vec2 vUv;',

    '//A full target quad. The cloud passes draw with a bare THREE.Camera whose matrices',
    "//are identity, so the plane's vertices are already in clip space.",
    'void main(){',
      'vUv = uv;',
      'gl_Position = vec4(position, 1.0);',
    '}',
  ].join('\n'),
  fragmentShader: [
    '//Temporal resolve for the cloud map. Upsamples the half resolution march map to',
    '//the full map and folds it into the history, so the blue noise jitter in the',
    '//march averages away into a smooth, very slightly soft image.',
    '//',
    '//Because the map is indexed by direction rather than by screen pixel, turning',
    '//the head moves nothing in it. The only reprojection left is for things that',
    '//genuinely move the clouds relative to the viewer: the wind, and the camera',
    '//walking around underneath them.',

    'varying vec2 vUv;',

    'uniform sampler2D cloudMarchMap;',
    'uniform sampler2D cloudHistoryMap;',
    "uniform vec2 cloudJitter;             //This frame's march jitter, in march texels",
    'uniform vec2 cloudMarchSize;          //March map size in texels',
    'uniform vec2 cloudMarchTexelSize;     //1 / march map size',
    'uniform vec3 cloudReprojectionShift;  //Camera motion minus wind motion since last frame, sky frame, meters',
    'uniform float cloudReprojectionHeight;//Height of the cloud layer we reproject against, meters above the observer',
    'uniform float cloudEarthRadius;       //Meters',
    'uniform float cloudCutoffDistance;    //Meters',
    'uniform float cloudHistoryBlend;      //Weight of the new frame where this frame has a sample right here. 1.0 discards the history.',
    'uniform vec2 cloudResolveSize;        //Resolve (output) map size in texels',

    '//Must match CLOUD_MAP_K in cloud-march.glsl, atmosphere-pass.glsl and CloudRenderer.js',
    'const float CLOUD_MAP_K = 1.0723687100246826;',

    '//How far outside the local min/max the history may sit before it is clipped, in',
    '//standard deviations. Lower rejects ghosts harder but lets more of the march noise',
    '//through; 1.25 is the usual compromise for noisy half resolution inputs.',
    'const float CLOUD_TAA_VARIANCE_GAMMA = 1.25;',

    "//Falloff of a march sample's weight with its distance from this texel, in output",
    '//texels: exp(-k * d^2), the usual Gaussian fit to Blackman-Harris. The march map is',
    "//half resolution, so on any one frame a texel's nearest sample sits anywhere up to",
    '//about 1.4 output texels away. Weighting by that distance, rather than handing',
    '//every texel the same bilinear blend of its neighbours, means each texel mostly',
    '//learns from the frames whose jitter put a sample close to it -- which is what',
    '//turns sixteen jittered half resolution frames into a full resolution image',
    '//instead of a blurred half resolution one.',
    '//2.29 is the textbook value; 3.0 leans a little further towards the nearest sample,',
    '//which keeps more of the cauliflower detail that the nine tap reconstruction',
    '//otherwise softens.',
    'const float CLOUD_TAA_SAMPLE_SHARPNESS = 3.0;',

    'vec2 cloudDirectionToUV(vec3 direction){',
      'return 0.5 + 0.5 * direction.xz / ((1.0 + direction.y) * CLOUD_MAP_K);',
    '}',

    'vec3 cloudUVToDirection(vec2 uv){',
      'vec2 p = (2.0 * uv - 1.0) * CLOUD_MAP_K;',
      'float pSquared = dot(p, p);',
      'return vec3(2.0 * p.x, 1.0 - pSquared, 2.0 * p.y) / (1.0 + pSquared);',
    '}',

    'vec3 RGBToYCoCg(vec3 c){',
      'return vec3(',
        '0.25 * c.r + 0.5 * c.g + 0.25 * c.b,',
        '0.5 * c.r - 0.5 * c.b,',
        '-0.25 * c.r + 0.5 * c.g - 0.25 * c.b',
      ');',
    '}',

    'vec3 YCoCgToRGB(vec3 c){',
      'return vec3(c.x + c.y - c.z, c.x + c.z, c.x - c.y - c.z);',
    '}',

    '//Clip towards the centre of the box rather than clamping each axis, so a history',
    '//colour outside the box moves along the line to the local mean and keeps its hue',
    '//(Playdead, INSIDE, GDC 2016).',
    'vec4 clipToAABB(vec4 history, vec4 boxMin, vec4 boxMax){',
      'vec4 center = 0.5 * (boxMax + boxMin);',
      'vec4 extents = 0.5 * (boxMax - boxMin) + 1e-5;',
      'vec4 offset = history - center;',
      'vec4 unitOffset = abs(offset / extents);',
      'float maxUnit = max(max(unitOffset.x, unitOffset.y), max(unitOffset.z, unitOffset.w));',
      'return maxUnit > 1.0 ? center + offset / maxUnit : history;',
    '}',

    '//Catmull-Rom history fetch in nine bilinear taps (Jimenez, Filmic SMAA). The',
    '//history is resampled at a fractional offset every frame while the wind carries',
    '//it along, and a plain bilinear fetch softens it a little on every one of those',
    '//resamples -- over a dozen frames that compounds into visible blur.',
    'vec4 sampleHistoryCatmullRom(sampler2D historyMap, vec2 uv, vec2 size){',
      'vec2 samplePosition = uv * size;',
      'vec2 texPos1 = floor(samplePosition - 0.5) + 0.5;',
      'vec2 f = samplePosition - texPos1;',
      'vec2 w0 = f * (-0.5 + f * (1.0 - 0.5 * f));',
      'vec2 w1 = 1.0 + f * f * (-2.5 + 1.5 * f);',
      'vec2 w2 = f * (0.5 + f * (2.0 - 1.5 * f));',
      'vec2 w3 = f * f * (-0.5 + 0.5 * f);',
      'vec2 w12 = w1 + w2;',
      'vec2 offset12 = w2 / w12;',
      'vec2 texPos0 = (texPos1 - 1.0) / size;',
      'vec2 texPos3 = (texPos1 + 2.0) / size;',
      'vec2 texPos12 = (texPos1 + offset12) / size;',

      'vec4 result = vec4(0.0);',
      'result += texture(historyMap, vec2(texPos0.x, texPos0.y)) * w0.x * w0.y;',
      'result += texture(historyMap, vec2(texPos12.x, texPos0.y)) * w12.x * w0.y;',
      'result += texture(historyMap, vec2(texPos3.x, texPos0.y)) * w3.x * w0.y;',
      'result += texture(historyMap, vec2(texPos0.x, texPos12.y)) * w0.x * w12.y;',
      'result += texture(historyMap, vec2(texPos12.x, texPos12.y)) * w12.x * w12.y;',
      'result += texture(historyMap, vec2(texPos3.x, texPos12.y)) * w3.x * w12.y;',
      'result += texture(historyMap, vec2(texPos0.x, texPos3.y)) * w0.x * w3.y;',
      'result += texture(historyMap, vec2(texPos12.x, texPos3.y)) * w12.x * w3.y;',
      'result += texture(historyMap, vec2(texPos3.x, texPos3.y)) * w3.x * w3.y;',

      '//Catmull-Rom has negative lobes; keep them from pushing radiance or opacity below zero.',
      'return max(result, vec4(0.0));',
    '}',

    'void main(){',
      'vec2 p = (2.0 * vUv - 1.0);',
      'if(dot(p, p) > 1.0){',
        'gl_FragColor = vec4(0.0);',
        'return;',
      '}',

      '//The march texel k holds the value at (k + 0.5 + jitter) / size. Centre on the',
      '//one whose sample landed nearest this texel.',
      'vec2 marchPosition = vUv * cloudMarchSize - 0.5 - cloudJitter;',
      'vec2 nearestSample = floor(marchPosition + 0.5);',
      'ivec2 maxTexel = ivec2(cloudMarchSize) - 1;',
      'ivec2 centerTexel = clamp(ivec2(nearestSample), ivec2(0), maxTexel);',
      'vec2 marchToOutputTexels = cloudResolveSize / cloudMarchSize;',

      '//One pass over the 3x3 march samples around us does two jobs:',
      "//  - Reconstruct this frame's value here, weighting each sample by how close it",
      '//    landed. Using all nine rather than only the nearest keeps the per frame',
      '//    noise down -- a single sample at a cloud edge is either cloud or sky, and',
      '//    feeding that straight in is what made edges flicker. The weights are sharp',
      '//    enough that a sample right on top of us still dominates, which is what',
      '//    builds full resolution detail over the jitter sequence.',
      '//  - Neighbourhood statistics for clipping the history, in YCoCg so the box hugs',
      '//    luminance and chroma separately.',
      'vec4 current = vec4(0.0);',
      'float totalSampleWeight = 0.0;',
      'vec4 moment1 = vec4(0.0);',
      'vec4 moment2 = vec4(0.0);',
      'for(int y = -1; y <= 1; ++y){',
        'for(int x = -1; x <= 1; ++x){',
          'ivec2 texel = clamp(centerTexel + ivec2(x, y), ivec2(0), maxTexel);',
          'vec4 s = texelFetch(cloudMarchMap, texel, 0);',
          'vec2 offset = (marchPosition - vec2(texel)) * marchToOutputTexels;',
          'float w = exp(-CLOUD_TAA_SAMPLE_SHARPNESS * dot(offset, offset));',
          'current += s * w;',
          'totalSampleWeight += w;',

          's = vec4(RGBToYCoCg(s.rgb), s.a);',
          'moment1 += s;',
          'moment2 += s * s;',
        '}',
      '}',
      'current /= max(totalSampleWeight, 1e-4);',
      '//How much evidence this frame has for this texel, ~1 when a sample sits on top',
      '//of it, less between samples.',
      'float sampleWeight = clamp(totalSampleWeight, 0.0, 1.0);',
      'vec4 mean = moment1 / 9.0;',
      'vec4 sigma = sqrt(max(moment2 / 9.0 - mean * mean, 0.0));',
      'vec4 boxMin = mean - CLOUD_TAA_VARIANCE_GAMMA * sigma;',
      'vec4 boxMax = mean + CLOUD_TAA_VARIANCE_GAMMA * sigma;',

      '//Reproject. We do not store depth, so estimate it as the distance to a sphere at',
      '//the height of the cloud layer -- the layer is thin next to its distance, so this',
      '//is close everywhere that matters. The point that is here now was at',
      "//(here + shift) relative to last frame's camera.",
      'vec3 direction = cloudUVToDirection(vUv);',
      'float r = cloudEarthRadius;',
      'float h = cloudReprojectionHeight;',
      'float mu = max(direction.y, 0.0);',
      'float depth = -r * mu + sqrt(r * r * mu * mu + 2.0 * r * h + h * h);',
      'depth = min(depth, cloudCutoffDistance);',
      'vec3 previousDirection = normalize(direction * depth + cloudReprojectionShift);',
      'vec2 previousUV = cloudDirectionToUV(previousDirection);',
      'vec2 previousP = 2.0 * previousUV - 1.0;',
      'bool historyValid = previousDirection.y > -0.07 && dot(previousP, previousP) <= 1.0;',

      'vec4 result;',
      'if(!historyValid || cloudHistoryBlend >= 1.0){',
        '//Nothing to accumulate against, so reconstruct from this frame alone -- a smooth',
        '//bilinear upsample rather than the blocky nearest sample.',
        'result = texture(cloudMarchMap, vUv - cloudJitter * cloudMarchTexelSize);',
      '}',
      'else{',
        'float blend = cloudHistoryBlend * sampleWeight;',
        'vec4 history = sampleHistoryCatmullRom(cloudHistoryMap, previousUV, cloudResolveSize);',
        'history = vec4(RGBToYCoCg(history.rgb), history.a);',
        'history = clipToAABB(history, boxMin, boxMax);',
        'history = vec4(YCoCgToRGB(history.rgb), history.a);',

        '//A plain lerp, deliberately. The usual luminance weighted blend (Karis) assumes',
        '//every sample is a colour over the same background; here clear sky is stored',
        '//as zero, which that weighting treats as the most trustworthy sample of all, so',
        '//every cloud edge got dragged towards empty -- thin, eroded, flickering clouds.',
        '//The map is premultiplied, so a straight average is exactly right.',
        'result = mix(history, current, blend);',
      '}',

      'gl_FragColor = max(result, vec4(0.0));',
    '}',
  ].join('\n')
};
