StarrySky.Materials.Clouds.cloudNoiseMaterial = {
  uniforms: function(){
    return {
      slice: {value: 0.0},
      depth: {value: 1.0},
      noiseMode: {value: 0}
    };
  },
  fragmentShader: [
    '//Bakes the three tileable noise textures the clouds are built from, one layer at a',
    '//time (see CloudLUTLibrary.js). Everything here repeats seamlessly: every lattice is',
    '//wrapped by its period before it is hashed, so the right edge of the texture meets',
    '//the left edge, and the top of the volume meets the bottom.',
    '//',
    '//  noiseMode 0 -- base shape, 128^3',
    '//    r  the cloud SHAPE: Perlin-Worley remapped by a Worley fBm, the Nubis / GPU Pro 7',
    "//       recipe as baked by takram's three-clouds (MIT). This is what erodes the",
    '//       coverage into billowing masses (see cloud-density.glsl).',
    '//    g  Worley fBm, 8 cells     b  Worley fBm, 16 cells    a  Worley fBm, 32 cells',
    '//  noiseMode 1 -- detail, 32^3',
    '//    r  Worley fBm of fBms at 2 to 16 cells (takram), eroding the edges: wispy at',
    '//       the bottom of a cloud, billowy at the top',
    '//    g  Worley fBm, 4 cells     b  Worley fBm, 8 cells',
    '//  noiseMode 2 -- weather, 512^2 (2D)',
    '//    r  cloud footprints: a Worley fBm, 16 cells, 0..1',
    '//    g  free',
    '//    b  coverage variation, kilometres wide    a  species variation',
    '//',
    '//References: Schneider, "The Real-time Volumetric Cloudscapes of Horizon Zero Dawn",',
    "//SIGGRAPH 2015; Hillaire's TileableVolumeNoise; and takram-design-engineering's",
    '//three-geospatial clouds (MIT), whose shape, detail and weather recipes these follow.',

    'uniform float slice;',
    'uniform float depth;',
    'uniform int noiseMode;',

    '//PCG3D (Jarzynski and Olano, 2020): a well mixed integer hash, free of the sin()',
    "//precision artifacts the old baker's hash had.",
    'uvec3 pcg3d(uvec3 v){',
      'v = v * 1664525u + 1013904223u;',
      'v.x += v.y * v.z; v.y += v.z * v.x; v.z += v.x * v.y;',
      'v ^= v >> 16u;',
      'v.x += v.y * v.z; v.y += v.z * v.x; v.z += v.x * v.y;',
      'return v;',
    '}',

    '//Cells must already be wrapped into [0, period), so they are never negative.',
    'vec3 hash33(vec3 cell, float seed){',
      'return vec3(pcg3d(uvec3(cell) + uvec3(uint(seed) * 7919u))) * (1.0 / 4294967295.0);',
    '}',

    '//Tileable Worley noise, inverted so feature points are 1 and the gaps fall to 0.',
    'float worley(vec3 p, vec3 period, float seed){',
      'vec3 x = p * period;',
      'vec3 cell = floor(x);',
      'vec3 f = x - cell;',
      'float minDistanceSquared = 1e9;',
      'for(int k = -1; k <= 1; ++k){',
        'for(int j = -1; j <= 1; ++j){',
          'for(int i = -1; i <= 1; ++i){',
            'vec3 offset = vec3(float(i), float(j), float(k));',
            'vec3 wrappedCell = mod(cell + offset, period);',
            'vec3 featurePoint = offset + hash33(wrappedCell, seed);',
            'vec3 difference = featurePoint - f;',
            'minDistanceSquared = min(minDistanceSquared, dot(difference, difference));',
          '}',
        '}',
      '}',
      'return 1.0 - clamp(sqrt(minDistanceSquared), 0.0, 1.0);',
    '}',

    '//Worley noise as takram (after Hillaire) bakes it: one minus the SQUARED distance,',
    '//which gives rounder, fuller cells than the plain distance.',
    'float worleySquared(vec3 p, vec3 period, float seed){',
      'float w = 1.0 - worley(p, period, seed);',
      'return 1.0 - w * w;',
    '}',

    'float worleySquaredFbm3(vec3 p, float c0, float c1, float c2, float seed){',
      'return 0.625 * worleySquared(p, vec3(c0), seed)',
        '+ 0.25 * worleySquared(p, vec3(c1), seed + 1.0)',
        '+ 0.125 * worleySquared(p, vec3(c2), seed + 2.0);',
    '}',

    '//An fBm of fBms over four octaves of Worley noise, c to 8c cells (takram).',
    'float worleyNestedFbm(vec3 p, float c, float seed){',
      'vec4 n = vec4(',
        'worleySquared(p, vec3(c), seed),',
        'worleySquared(p, vec3(2.0 * c), seed + 1.0),',
        'worleySquared(p, vec3(4.0 * c), seed + 2.0),',
        'worleySquared(p, vec3(8.0 * c), seed + 3.0)',
      ');',
      'vec3 fbm = vec3(',
        'dot(n.xyz, vec3(0.625, 0.25, 0.125)),',
        'dot(n.yzw, vec3(0.625, 0.25, 0.125)),',
        'dot(n.zw, vec2(0.75, 0.25))',
      ');',
      'return dot(fbm, vec3(0.625, 0.25, 0.125));',
    '}',

    '//Three octaves, weights from Schneider.',
    'float worleyFbm(vec3 p, float cells, float seed){',
      'vec3 period = vec3(cells);',
      'return worley(p, period, seed) * 0.625',
        '+ worley(p, period * 2.0, seed + 1.0) * 0.25',
        '+ worley(p, period * 4.0, seed + 2.0) * 0.125;',
    '}',

    '//Tileable gradient (Perlin) noise with a quintic fade, roughly in [-1, 1].',
    'float perlin(vec3 p, vec3 period, float seed){',
      'vec3 x = p * period;',
      'vec3 i0 = floor(x);',
      'vec3 f = x - i0;',
      'vec3 u = f * f * f * (f * (f * 6.0 - 15.0) + 10.0);',

      'float corners[8];',
      'for(int c = 0; c < 8; ++c){',
        'vec3 corner = vec3(float(c & 1), float((c >> 1) & 1), float((c >> 2) & 1));',
        'vec3 gradient = normalize(hash33(mod(i0 + corner, period), seed) * 2.0 - 1.0 + 1e-5);',
        'corners[c] = dot(gradient, f - corner);',
      '}',
      'float x00 = mix(corners[0], corners[1], u.x);',
      'float x10 = mix(corners[2], corners[3], u.x);',
      'float x01 = mix(corners[4], corners[5], u.x);',
      'float x11 = mix(corners[6], corners[7], u.x);',
      'return mix(mix(x00, x10, u.y), mix(x01, x11, u.y), u.z) * 1.5;',
    '}',

    'float perlinFbm(vec3 p, vec3 period, int octaves, float seed){',
      'float sum = 0.0;',
      'float amplitude = 0.5;',
      'float normalization = 0.0;',
      'for(int o = 0; o < 8; ++o){',
        'if(o >= octaves){',
          'break;',
        '}',
        'sum += amplitude * perlin(p, period, seed + float(o));',
        'normalization += amplitude;',
        'period *= 2.0;',
        'amplitude *= 0.5;',
      '}',
      'return sum / normalization;',
    '}',

    'float remap(float x, float a, float b, float c, float d){',
      'return c + (x - a) * (d - c) / (b - a);',
    '}',

    'void main(){',
      'vec2 uv = gl_FragCoord.xy / resolution.xy;',

      'if(noiseMode == 0){',
        'vec3 p = vec3(uv, (slice + 0.5) / depth);',
        '//The shape, exactly as takram bakes it: Perlin (3 octaves from 8 periods, only',
        '//its upper half kept) lifted into [Worley fBm, 1], then remapped by a second,',
        '//finer Worley fBm. The remap is what turns soft noise into clumped billows.',
        'float perlinNoise = clamp(perlinFbm(p, vec3(8.0), 3, 10.0), 0.0, 1.0);',
        'float perlinWorley = remap(perlinNoise, 0.0, 1.0, worleySquaredFbm3(p, 8.0, 32.0, 56.0, 15.0), 1.0);',
        'float shape = clamp(remap(perlinWorley, worleyNestedFbm(p, 8.0, 25.0) - 1.0, 1.0, 0.0, 1.0), 0.0, 1.0);',
        'float worley8 = worleyFbm(p, 8.0, 20.0);',
        'gl_FragColor = vec4(shape, worley8, worleyFbm(p, 16.0, 30.0), worleyFbm(p, 32.0, 40.0));',
      '}',
      'else if(noiseMode == 1){',
        'vec3 p = vec3(uv, (slice + 0.5) / depth);',
        'gl_FragColor = vec4(worleyNestedFbm(p, 2.0, 50.0), worleyFbm(p, 4.0, 60.0), worleyFbm(p, 8.0, 70.0), 1.0);',
      '}',
      'else{',
        '//2D, so z is pinned at 0 and never wraps.',
        'vec3 p = vec3(uv, 0.0);',

        '//Footprints: a four octave Worley fBm, 16 cells, normalized to 0..1. The density',
        '//thresholds it by coverage, so each cloud is a rounded blob of the low octave',
        "//with a lumpy outline from the higher ones. takram's gain of 0.95 (almost equal",
        '//octaves) made every outline ragged at every scale, and the sky came out as',
        '//confetti rather than separate heaps; 0.5 is a plain fBm.',
        'float footprint = 0.0;',
        'float amplitude = 1.0;',
        'float amplitudeSum = 0.0;',
        'float cells = 16.0;',
        'for(int o = 0; o < 4; ++o){',
          'footprint += amplitude * worleySquared(p, vec3(cells, cells, 1.0), 140.0 + float(o));',
          'amplitudeSum += amplitude;',
          'cells *= 2.0;',
          'amplitude *= 0.5;',
        '}',
        'footprint /= amplitudeSum;',

        'float coverage = clamp(0.5 + 0.75 * perlinFbm(p, vec3(4.0, 4.0, 1.0), 5, 80.0), 0.0, 1.0);',
        'float species = clamp(0.5 + 0.9 * perlinFbm(p, vec3(2.0, 2.0, 1.0), 3, 90.0), 0.0, 1.0);',
        'gl_FragColor = vec4(footprint, 0.0, coverage, species);',
      '}',
    '}',
  ].join('\n')
};
